import Head from 'next/head'
import Header from '../components/Header'
import VideoBox from '../components/VideoBox'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Advertisement Research</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex-row items-center'>

      {/* Header */}
      <Header />
      <VideoBox/>
      

      </div>

    </div>
  )
}
 